# Generated by Django 3.0.6 on 2020-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('active_region', models.CharField(max_length=256)),
                ('avatar', models.ImageField(upload_to='team-profile')),
                ('bio', models.TextField(blank=True, default='')),
                ('is_solo', models.BooleanField(default='True')),
                ('genres', models.ManyToManyField(to='core.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
