# Generated by Django 3.0.6 on 2020-05-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(upload_to='team-profile'),
        ),
    ]
