# Generated by Django 3.0.4 on 2020-04-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='user',
            new_name='users',
        ),
    ]
