# Generated by Django 3.0.5 on 2020-04-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200422_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
