# Generated by Django 3.0.6 on 2020-05-28 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0003_auto_20200514_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='positions',
        ),
        migrations.AddField(
            model_name='team',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_solo',
            field=models.BooleanField(default='True'),
        ),
    ]
