# Generated by Django 3.0.6 on 2020-05-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200528_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='users',
            new_name='members',
        ),
    ]
