# Generated by Django 3.0.6 on 2020-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_borough_city'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='borough',
        ),
        migrations.AddField(
            model_name='user',
            name='borough',
            field=models.ManyToManyField(related_name='users', to='core.Borough'),
        ),
    ]
