# Generated by Django 3.0.6 on 2020-05-06 17:48

import core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200507_0248'),
        ('users', '0003_auto_20200507_0041'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.managers.CustomManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='positions',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='core.Position'),
        ),
    ]
