# Generated by Django 3.0.6 on 2020-05-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200527_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
