# Generated by Django 3.0.6 on 2020-05-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200507_0248'),
        ('users', '0004_auto_20200507_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.Position'),
        ),
    ]
