# Generated by Django 3.0.6 on 2020-05-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200527_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_first',
            field=models.BooleanField(default=True),
        ),
    ]
