# Generated by Django 3.0.6 on 2020-05-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200527_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_login',
            field=models.BooleanField(default=False),
        ),
    ]
