# Generated by Django 3.0.6 on 2020-06-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200625_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_method',
            new_name='login_methods',
        ),
    ]
