# Generated by Django 3.0.6 on 2020-05-28 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_borough_city'),
        ('users', '0006_user_email_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='borough',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.CreateModel(
            name='ActiveRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_regions', to='core.Borough')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_reigions', to='core.City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_regions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
