# Generated by Django 3.0.6 on 2020-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('composer', models.CharField(blank=True, default='', max_length=64)),
                ('lyricist', models.CharField(blank=True, default='', max_length=64)),
                ('singer', models.CharField(blank=True, default='', max_length=64)),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Base Song',
                'verbose_name_plural': 'Base Songs',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True)),
                ('content_file', models.FileField(upload_to='contents')),
                ('content_photo', models.ImageField(upload_to='contents-photo')),
                ('content_title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('lyrics', models.TextField(blank=True, default='')),
                ('is_exposure', models.BooleanField(default=False)),
                ('content_type', models.CharField(choices=[('cover', 'Cover'), ('own', 'Own'), ('clip', 'Clip')], max_length=16)),
                ('genres', models.ManyToManyField(to='core.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
