# Generated by Django 3.0.6 on 2020-06-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_team'),
        ('contents', '0003_auto_20200611_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='projects.Project'),
        ),
    ]
