# Generated by Django 3.0.6 on 2020-06-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20200612_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_exposure',
        ),
        migrations.AddField(
            model_name='content',
            name='exposure_level',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('limited', 'Limited')], default=None, max_length=16),
        ),
    ]
