# Generated by Django 3.0.6 on 2020-06-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_auto_20200614_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='exposure_level',
            field=models.CharField(choices=[('public', '전체공개'), ('private', '비공개'), ('limited', '제한공개')], default=None, max_length=16),
        ),
    ]
