# Generated by Django 3.0.6 on 2020-05-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200510_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
    ]
