# Generated by Django 3.0.6 on 2020-05-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200509_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(upload_to='project-jacket'),
        ),
    ]
