# Generated by Django 3.0.6 on 2020-05-06 17:48

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200423_1444'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('objects', core.managers.CustomManager()),
            ],
        ),
    ]
