# Generated by Django 3.0.6 on 2020-05-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participants',
        ),
    ]
