# Generated by Django 3.0.6 on 2020-05-06 17:48

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listcategory',
            managers=[
                ('objects', core.managers.CustomManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='playlist',
            managers=[
                ('objects', core.managers.CustomManager()),
            ],
        ),
    ]
