# Generated by Django 3.0.6 on 2020-06-02 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
        ('contents', '0002_content_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecontent',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likecontent',
            name='target_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_contents', to='contents.Content'),
        ),
        migrations.AddField(
            model_name='hatecontent',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hate_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hatecontent',
            name='target_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hate_contents', to='contents.Content'),
        ),
        migrations.AddField(
            model_name='commenttocontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contents.Content'),
        ),
        migrations.AddField(
            model_name='commenttocontent',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
