# Generated by Django 3.0.4 on 2020-03-17 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('composer', models.CharField(max_length=64)),
                ('lyricist', models.CharField(max_length=64)),
                ('singer', models.CharField(max_length=64)),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='albums.Album')),
                ('base_song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='songs.BaseSong')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoveredSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('base_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_songs', to='songs.BaseSong')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_songs', to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
