# Generated by Django 3.0.4 on 2020-03-27 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20200327_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coveredsong',
            name='base_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_songs', to='songs.BaseSong'),
        ),
        migrations.AddField(
            model_name='coveredsong',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_songs', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='coveredsong',
            name='roles',
            field=models.ManyToManyField(related_name='covered_songs', to='songs.Role'),
        ),
    ]
