# Generated by Django 3.0.4 on 2020-03-19 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='base_song',
        ),
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.ManyToManyField(related_name='composed_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='lyricist',
            field=models.ManyToManyField(related_name='written_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ManyToManyField(related_name='sung_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
