# Generated by Django 3.0.4 on 2020-04-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200327_1809'),
        ('songs', '0002_auto_20200327_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.AddField(
            model_name='song',
            name='base_song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='covered_songs', to='songs.BaseSong'),
        ),
        migrations.AddField(
            model_name='song',
            name='is_covered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_songs', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='song',
            name='roles',
            field=models.ManyToManyField(related_name='covered_songs', to='songs.Role'),
        ),
        migrations.DeleteModel(
            name='CoveredSong',
        ),
    ]
