# Generated by Django 3.0.4 on 2020-04-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20200422_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basesong',
            options={'verbose_name': 'Base Song', 'verbose_name_plural': 'Base Songs'},
        ),
    ]
