# Generated by Django 3.0.5 on 2020-04-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20200423_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='roles',
        ),
        migrations.AddField(
            model_name='role',
            name='song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='songs.Song'),
        ),
    ]
