# Generated by Django 3.0.6 on 2020-05-06 17:48

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20200427_2112'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basesong',
            managers=[
                ('objects', core.managers.CustomManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('objects', core.managers.CustomManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='song',
            managers=[
                ('objects', core.managers.CustomManager()),
            ],
        ),
    ]
