# Generated by Django 3.0.6 on 2020-05-10 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('genres', models.ManyToManyField(related_name='recruits', to='core.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecruitedPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruited_positions', to='core.Position')),
                ('recruit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recruited_positions', to='recruitments.Recruit')),
            ],
        ),
    ]
