# Generated by Django 3.0.4 on 2020-04-22 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0002_recruit_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='recruitedposition',
            name='created',
        ),
        migrations.RemoveField(
            model_name='recruitedposition',
            name='updated',
        ),
        migrations.AddField(
            model_name='recruitedposition',
            name='recruit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recruited_positions', to='recruitments.Recruit'),
        ),
    ]
