# Generated by Django 3.0.5 on 2020-04-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0003_auto_20200422_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
