# Generated by Django 3.0.5 on 2020-04-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0004_auto_20200423_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='active_region',
        ),
    ]
