# Generated by Django 3.0.6 on 2020-05-06 17:48

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0005_remove_recruit_active_region'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recruit',
            managers=[
                ('objects', core.managers.CustomManager()),
            ],
        ),
    ]
