# Generated by Django 3.0.6 on 2020-06-02 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_auto_20200602_2102'),
        ('notifications', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onelikenotification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_like_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multilikenotification',
            name='like_contents',
            field=models.ManyToManyField(related_name='multi_like_notifications', to='comments.LikeContent'),
        ),
        migrations.AddField(
            model_name='multilikenotification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_like_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followingnotification',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_notifications', to='users.Following'),
        ),
        migrations.AddField(
            model_name='followingnotification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
